MSG (Eunexpected_eof,
     "予期しないEOFを検出しました"),
MSG (Eunterminated_comment,
     "コメントが終了していません"),
MSG (Eno_chars_following_single_escape,
     "‘\\’の後ろに文字がありません"),
MSG (Eunterminated_string,
     "文字列が終了していません"),
MSG (Eincomplete_dispatch_macro,
     "ディスパッチングマクロ定義が不完全です"),
MSG (Eillegal_character,
     "不正な文字です"),
MSG (Eunsupported_dispatch_macro,
     "未サポートのディスパッチングマクロです"),
MSG (Eundefined_dispatch_macro,
     "未定義のディスパッチングマクロです"),
MSG (Eno_following_hex_digits,
     "‘\\x’の後に16進文字がありません"),
MSG (Einvalid_dotted_list,
     "不正なドットリストです"),
MSG (Eunexpected_char,
     "予期しない文字です"),
MSG (Eunknown_char_name,
     "不正な文字名です"),
MSG (Echar_code_out_of_range,
     "文字コードが範囲外です"),
MSG (Einvalid_char_code_syntax,
     "不正な文字表記です"),
MSG (Eno_initializer_for_vector,
     "ベクタの初期化オブジェクトがありません"),
MSG (Etoo_many_initializer_for_vector,
     "ベクタの初期化オブジェクトが多すぎます"),
MSG (Elabel_number_redefined,
     "ラベルが再定義されました"),
MSG (Eundefined_label,
     "ラベルが定義されていません"),
MSG (Edot_only_token,
     "ドットのみのトークンです"),
MSG (Eno_label_for_number_equal,
     "‘#=’にラベルが指定されていません"),
MSG (Eno_label_for_number_number,
     "‘##’にラベルが指定されていません"),
MSG (Einvalid_midfix_parameter,
     "不正な間置引数が指定されました"),
MSG (Enot_allow_evaluation,
     "リード時の評価が許されていません"),
MSG (Enumber_R_parameter_out_of_range,
     "‘#R’の引数は2から36です"),
MSG (Ewrong_argument_for_number_plus,
     "‘#+’の条件が不正です"),
MSG (Ewrong_argument_for_number_minus,
     "‘#-’の条件が不正です"),
MSG (Ewrong_integer_format,
     "不正な整数のフォーマットです"),
MSG (Ebad_package_marker,
     "不正なパッケージマーカです"),
MSG (Epackage_marker_appears_end_of_token,
     "パッケージマーカがトークンの終わりにあります"),
MSG (Etwo_package_marker_appears_beginning_of_token,
     "2つのパッケージマーカがトークンの先頭にあります"),
MSG (Eexternal_symbol_not_found,
     "外部シンボルは見つかりません"),
MSG (Ecomma_atsign_after_backquote,
     "‘`’の後に‘,@’があります"),
MSG (Ecomma_dot_after_backquote,
     "‘`’の後に‘,.’があります"),
MSG (Emalformed_comma,
     "不正な‘,’です"),
MSG (Edotted_comma_atsign,
     "‘,@’がドットリストにあらわれました"),
MSG (Edotted_comma_dot,
     "‘,.’がドットリストにあらわれました"),
MSG (Edivision_by_zero,
     "0で除算しました"),
MSG (Eunbound_variable,
     "変数が定義されていません"),
MSG (Eundefined_function,
     "関数が定義されていません"),
MSG (Emodify_constant,
     "定数は変更できません"),
MSG (Einvalid_keyword_list,
     "不正なキーワードリストです"),
MSG (Einvalid_lambda_list,
     "不正なラムダリストです"),
MSG (Einvalid_function,
     "不正な関数です"),
MSG (Einvalid_variable_list,
     "不正な変数リストです"),
MSG (Ebad_macro_form,
     "不正なマクロフォームです"),
MSG (Einvalid_argument,
     "引数が不正です"),
MSG (Etype_error,
     "不正なデータ型です"),
MSG (Ebad_type_specifier,
     "型指定子が不正です"),
MSG (Erange_error,
     "範囲外の値です"),
MSG (Etoo_few_arguments,
     "引数が少なすぎます"),
MSG (Etoo_many_arguments,
     "引数が多すぎます"),
MSG (Estorage_condition,
     "メモリ不足です"),
MSG (Estack_overflow,
     "スタックオーバーフロー"),
MSG (Eformat_argument_exhausted,
     "引数が足りません"),
MSG (Eend_of_ctl_string,
     "制御文字列が途中で終わっています"),
MSG (Eargument_is_circle,
     "引数が循環しています"),
MSG (Etoo_many_parameters,
     "パラメータが多すぎます"),
MSG (Efmt_r_requires_2_36,
     "基数は2から36です"),
MSG (Esign_following_no_chars,
     "符号の後に文字がありません"),
MSG (Esign_following_not_digits,
     "符号の後に数字がありません"),
MSG (Equote_following_no_chars,
     "‘'’の後に文字がありません"),
MSG (Ecannot_backup,
     "引数をバックアップできません"),
MSG (Ecannot_goto,
     "引数の位置指定が範囲外です"),
MSG (Eillegal_colon,
     "不正な‘:’です"),
MSG (Eillegal_atsign,
     "不正な‘@’です"),
MSG (Eillegal_colon_atsign,
     "不正な‘:@’です"),
MSG (Eillegal_parameter_type,
     "パラメータの型が不正です"),
MSG (Eparameter_out_of_range,
     "パラメータの値が範囲外です"),
MSG (Eillegal_fmt_V_parameter,
     "Vパラメータの型が不正です"),
MSG (Eclose_paren_expected,
     "‘)’が見つかりません"),
MSG (Eclose_brace_expected,
     "‘}’が見つかりません"),
MSG (Eclose_bracket_expected,
     "‘]’が見つかりません"),
MSG (Egreater_than_expected,
     "‘>’が見つかりません"),
MSG (Etoo_many_conditional_form,
     "条件節が多すぎます"),
MSG (Eillegal_colon_circumflex,
     "不正な‘~:^’です"),
MSG (Eillegal_format_directive,
     "不正なformat指示子です"),
MSG (Ejustification_not_implemented,
     "justificationは実装されていません"),
MSG (Elists_length_different,
     "リストの長さが異なります"),
MSG (Etest_and_test_not_are_both_specified,
     "‘:test’と‘:test-not’が両方指定されています"),
MSG (Eis_special_variable,
     "スペシャル変数は定数にできません"),
MSG (Eis_constant_variable,
     "定数はスペシャル変数にできません"),
MSG (Evector_has_no_fill_pointer,
     "フィルポインタを持たないベクタです"),
MSG (Efill_pointer_is_zero,
     "フィルポインタが0です"),
MSG (Eelement_and_contents_are_both_specified,
     "‘:initial-element’と‘:initial-contents’が両方指定されています"),
MSG (Einitial_contents_has_wrong_length,
     "‘:initial-contents’の長さが指定された長さと一致しません"),
MSG (Epath_name_too_long,
     "パス名が長すぎます"),
MSG (Einvalid_if_does_not_exist_option,
     "不正な‘:if-does-not-exist’オプションです"),
MSG (Einvalid_if_exists_option,
     "不正な‘:if-exists’オプションです"),
MSG (Einvalid_direction_option,
     "不正な‘:direction’オプションです"),
MSG (Ecannot_create_file,
     "ファイルをオープンできません"),
MSG (Elabel_reference_self,
     "ラベル付けされたオブジェクト自身を参照しています"),
MSG (Epackage_already_exists,
     "同じ名前のパッケージが存在します"),
MSG (Epackage_value_is_not_package,
     "*package*の値がパッケージではありません"),
MSG (Eno_package,
     "パッケージが存在しません"),
MSG (Ecannot_use_keyword_package,
     "keywordパッケージはuseできません"),
MSG (Epackage_is_used,
     "パッケージは他のパッケージに使用されています"),
MSG (Eunable_to_unintern_shadowing_symbol,
     "シャドウイングシンボルはuninternできません"),
MSG (Eis_not_accessible_symbol,
     "アクセスできないシンボルです"),
MSG (Ecannot_export_because_name_conflict,
     "名前が衝突するためexportできません"),
MSG (Eunable_to_unexport_keyword_package,
     "keywordパッケージからunexportできません"),
MSG (Ecannot_import_because_name_conflict,
     "名前が衝突するためimportできません"),
MSG (Ecannot_use_because_name_conflict,
     "名前が衝突するためuseできません"),
MSG (Ecannot_access_symbol_from_home_package,
     "ホームパッケージからアクセスできません"),
MSG (Efile_not_found,
     "ファイルが見つかりません"),
MSG (Earithmetic_domain_error,
     "0の対数は未定義です"),
MSG (Efloating_point_overflow,
     "オーバーフローしました"),
MSG (Efloating_point_underflow,
     "アンダーフローしました"),
MSG (Ecannot_coerce_to,
     "型変換できません"),
MSG (Eundefined_struct,
     "未定義の構造体です"),
MSG (Einvalid_struct_syntax,
     "不正な構造体の構文です"),
MSG (Einvalid_slot_name,
     "不正なスロット名です"),
MSG (Erandom_state_is_not_random_state,
     "*random-state*の値がランダムステート型ではありません"),
MSG (Einvalid_random_state_initializer,
     "ランダムステートの初期化オブジェクトが不正です"),
MSG (Eread_only_buffer,
     "書込み禁止バッファです"),
MSG (Eis_character_special_file,
     "デバイスファイルです"),
MSG (Eundo_outside_region,
     "変更した場所が見えないのでアンドゥでけん"),
MSG (Eundo_information_not_kept,
     "このバッファはアンドゥの記録をしていません"),
MSG (Eno_undo_information,
     "これ以上アンドゥできません"),
MSG (Ecannot_redo_more,
     "これ以上リドゥできません"),
MSG (Edeleted_buffer,
     "削除されたバッファです"),
MSG (Equit,
     "Quit"),
MSG (Ekey_not_bound,
     "Key not bound"),
MSG (Mgarbage_collecting,
     "Garbage collecting..."),
MSG (Mgarbage_collecting_done,
     "Garbage collecting...done"),
MSG (Eno_mark_set_in_this_window,
     "マークが設定されていません"),
MSG (Ebad_interactive_specifier,
     "不正なinteractive指定子です"),
MSG (Enot_a_command,
     "不正なコマンドです"),
MSG (Eno_such_buffer,
     "バッファが見つかりません"),
MSG (Edeleted_window,
     "削除されたウィンドウです"),
MSG (Ecannot_split,
     "分割できません"),
MSG (Ecannot_split_minibuffer_window,
     "ミニバッファウィンドウは分割できません"),
MSG (Eonly_one_window,
     "カレントウィンドウは削除できません"),
MSG (Edeleted_marker,
     "削除されたマーカです"),
MSG (Emarker_on_different_buffer,
     "他のバッファのマーカです"),
MSG (Emarker_is_not_set,
     "マーカはセットされていません"),
MSG (Ecannot_change_window_size,
     "変更できません"),
MSG (Eattempt_to_use_minibuffer_recursively,
     "ミニバッファは再帰的に使用できません"),
MSG (Esilent_quit,
     ""),
MSG (Eempty_buffer_names_not_allowed,
     "バッファ名が空文字列です"),
MSG (Ebuffer_name_too_long,
     "バッファ名が長すきます"),
MSG (Ecannot_switch_in_minibuffer_window,
     "ミニバッファウィンドウではバッファの変更はできません"),
MSG (Eis_a_directory,
     "指定されたパスはディレクトリです"),
MSG (Ecannot_specify_shift_bit,
     "SHIFTは指定できません"),
MSG (Ecannot_delete_backup_file,
     "すでに存在するバックアップファイルの削除ができません"),
MSG (Mcannot_create_numbered_backup_file,
     "番号付きバックアップファイルが作成できません"),
MSG (Mbuffer_needs_not_save,
     "保存する必要はありません"),
MSG (Mbuffer_is_truncated,
     "このバッファは中途半端にファイルを読み込んでいます。\n"
     "このまま保存するとファイルの後半が失われる可能性があります。\n"
     "保存しますか?"),
MSG (Eno_file_name,
     "ファイル名がありません"),
MSG (Eis_write_protected,
     "書込み禁止ファイルです"),
MSG (Mdisk_file_has_changed,
     "知らない間にファイルの日付が変わっています。保存しますか?"),
MSG (Ecannot_make_temp_file_name,
     "一時ファイルが作成できません"),
MSG (Mwriting,
     "保存中..."),
MSG (Ecannot_create_backup_file,
     "バックアップファイルが作成できません"),
MSG (Mauto_saving,
     "自動セーブ中...ちょっと待ってね"),
MSG (Mauto_saving_done,
     "自動セーブ終わり"),
MSG (Ewrite_error,
     "書き込みエラー"),
MSG (MFwrote_n_lines,
     "%d行"),
MSG (Ere_invalid_pattern,
     "不正なパターンです"),
MSG (Ere_unmatched_lbrace,
     "‘\\{’に対応する‘\\}’がありません"),
MSG (Ere_malformed_repeat_count,
     "‘\\{M,N\\}’のフォーマットが不正です"),
MSG (Ere_nesting_too_deep,
     "グルーピングのネストが深すぎます"),
MSG (Ere_unmatched_rparen,
     "‘\\)’に対応する‘\\(’がありません"),
MSG (Ere_unmatched_lparen,
     "‘\\(’に対応する‘\\)’がありません"),
MSG (Eunmatched_bracket,
     "‘[’に対応する‘]’がありません"),
MSG (Einvalid_syntax_spec,
     "不正なシンタックス指定子です"),
MSG (Einvalid_integer_format,
     "不正な数値の形式です"),
MSG (Enot_a_directory,
     "指定されたパスはディレクトリではありません"),
MSG (Munbalanced_parenthesis,
     "対応する括弧が見つかりません"),
MSG (Munmatched_parenthesis,
     "一致する括弧が見つかりません"),
MSG (Econtaining_expression_ends_prematurely,
     "式が中途半端に終了しています"),
MSG (Munbalanced_else,
     "‘else’に対応する‘if’がありません"),
MSG (Melse_not_within_a_conditional,
     "‘else’が妙な場所にあります"),
MSG (Ecreate_thread_failed,
     "スレッドが作成できません"),
MSG (Msubprocesses_are_running,
     "サブプロセスが走っています。こいつらを死なして終了しますか?"),
MSG (Esubprocess_is_already_running,
     "すでにサブプロセスが走っているため実行できません"),
MSG (Ebuffer_has_subprocess,
     "サブプロセスが走っています。"),
MSG (Mfile_has_changed_on_disk,
     "知らない間にファイルの日付が変わっています。\n編集を継続しますか?"),
MSG (Eedit_canceled,
     "キャンセルされました"),
MSG (Mmodified_buffers_exist,
     "%d個のバッファが変更されています。セーブしないで終了しますか?"),
MSG (Euninitialized_menu_item,
     "初期化されていないメニューです"),
MSG (Eis_not_popup_menu,
     "ポップアップメニューではありません"),
MSG (Etoo_many_menu_items,
     "メニュー項目が多すぎます"),
MSG (Einvalid_dialog_format,
     "ダイアログのフォーマットが不正です"),
MSG (Einvalid_dialog_font,
     "不正なダイアログフォントです"),
MSG (Einvalid_dialog_item,
     "不正なダイアログアイテムです"),
MSG (Einvalid_dialog_caption,
     "不正なダイアログキャプションです"),
MSG (Eunknown_dialog_option,
     "不正なダイアログオプションです"),
MSG (Ehiragana_and_katakana_are_both_specified,
     "‘:hiragana’と‘:katakana’が両方指定されています"),
MSG (Einvalid_byte_code,
     "バイトコードが壊れています"),
MSG (Mfile_has_already_locked,
     "誰かがすでに同じファイルを編集しています。\n編集を継続しますか?"),
MSG (Ekbd_macro_called_recursively,
     "キーボードマクロは再帰的に実行できません"),
MSG (Eline_spacing_must_0_to_30,
     "行間は0から30ピクセルです"),
MSG (Edde_error,
     "DDEでエラーが発生しました"),
MSG (Edde_timeout,
     "DDE要求がタイムアウトしました"),
MSG (Edde_busy,
     "DDEサーバーがBUSYです"),
MSG (Edde_low_memory,
     "サーバー先行状態です"),
MSG (Edde_no_conv,
     "DDE対話が確立できません"),
MSG (Edde_not_processed,
     "トランザクションの実行に失敗しました"),
MSG (Edde_server_died,
     "サーバーが終了しました"),
MSG (Edde_terminated_transaction,
     "終了したトランザクションです"),
MSG (Ekbd_input_is_disabled,
     "キーボードからの入力はできません"),
MSG (Efiler_is_not_open,
     "ファイラがオープンされていません"),
MSG (Efiler_is_not_in_dual_window_mode,
     "ファイラが2画面モードではありません"),
MSG (Einvalid_if_access_denied_option,
     "不正な‘:if-access-denied’オプションです"),
MSG (Eassoc_incomplete,
     "ファイル名の関連付けが不完全、または無効です"),
MSG (Eno_assoc,
     "指定されたファイル名拡張子には、アプリケーションが関連付けられていません"),
MSG (Einvalid_dictionary,
     "辞書が壊れています"),
MSG (ARC_ERROR_DISK_SPACE,
     "解凍する為のディスクの空きが足りません"),
MSG (ARC_ERROR_READ_ONLY,
     "解凍先のファイルはリードオンリーです"),
MSG (ARC_ERROR_USER_SKIP,
     "ユーザーによって解凍をスキップされました"),
MSG (ARC_ERROR_UNKNOWN_TYPE,
     "格納ファイルの種類が不明です"),
MSG (ARC_ERROR_METHOD,
     "UNZIP32.DLL で扱えない格納モードで格納されています"),
MSG (ARC_ERROR_PASSWORD_FILE,
     "格納ファイルにパスワードがかかっています"),
MSG (ARC_ERROR_VERSION,
     "格納ファイルの形式が未対応のバージョンです"),
MSG (ARC_ERROR_FILE_CRC,
     "格納ファイルのチェックサムが合っていません"),
MSG (ARC_ERROR_FILE_OPEN,
     "解凍時にファイルを開けませんでした"),
MSG (ARC_ERROR_MORE_FRESH,
     "より新しいファイルが解凍先に存在しています"),
MSG (ARC_ERROR_NOT_EXIST,
     "ファイルは解凍先に存在していません"),
MSG (ARC_ERROR_ALREADY_EXIST,
     "ファイルが解凍先に既に存在しています"),
MSG (ARC_ERROR_TOO_MANY_FILES,
     "格納ファイル数が限界を越えています"),
MSG (ARC_ERROR_DIRECTORY,
     "ディレクトリが作成できません"),
MSG (ARC_ERROR_CANNOT_WRITE,
     "解凍中に書き込みエラーが生じました"),
MSG (ARC_ERROR_HUFFMAN_CODE,
     "アーカイブファイルのハフマンコードが壊れています"),
MSG (ARC_ERROR_COMMENT_HEADER,
     "アーカイブファイルのコメントヘッダが壊れています"),
MSG (ARC_ERROR_HEADER_CRC,
     "アーカイブファイルのヘッダのチェックサムが合っていません"),
MSG (ARC_ERROR_HEADER_BROKEN,
     "アーカイバファイルのヘッダが壊れています"),
MSG (ARC_ERROR_ARC_FILE_OPEN,
     "アーカイブファイルを開く事が出来ません"),
MSG (ARC_ERROR_NOT_ARC_FILE,
     "指定したファイルは、アーカイブファイルではありません"),
MSG (ARC_ERROR_CANNOT_READ,
     "アーカイブファイルの読み込み時に読み込みエラーが出ました"),
MSG (ARC_ERROR_FILE_STYLE,
     "指定されたファイルはアーカイブファイルではありません"),
MSG (ARC_ERROR_COMMAND_NAME,
     "コマンド指定が間違っています"),
MSG (ARC_ERROR_MORE_HEAP_MEMORY,
     "作業用のためのヒープメモリが不足しています"),
MSG (ARC_ERROR_ENOUGH_MEMORY,
     "グローバルメモリが不足しています"),
MSG (ARC_ERROR_DEAD,
     "アーカイバDLLが死にました"),
MSG (Eextract_error,
     "解凍中にエラーが発生しました"),
MSG (Ecompress_error,
     "圧縮中にエラーが発生しました"),
MSG (Ecompress_not_supported,
     "圧縮はサポートしていません"),
MSG (Epower_number_too_large,
     "べきが大きすぎます"),
MSG (Ezero_denominator,
     "分母が0です"),
MSG (Ebignum_overflow,
     "整数演算がオーバーフローしました"),
MSG (Einvalid_complex_syntax,
     "不正な複素数の構文です"),
MSG (Evector_is_not_adjustable,
     "サイズ変更可能なベクタではありません"),
MSG (Eunmatch_array_type,
     "共有する配列の型が違います"),
MSG (Edisplaced_to_array_too_small,
     "共有する配列が小さすぎます"),
MSG (Earray_size_too_large,
     "配列のサイズが大きすぎます"),
MSG (Earray_rank_too_large,
     "配列のランクが大きすぎます"),
MSG (Earray_type_mismatch,
     "配列の型が異なります"),
MSG (Ecannot_replace_displace_array,
     "共有している配列は交換できません"),
MSG (Eis_not_adjustable_array,
     "変更可能でない配列は交換できません"),
MSG (Eis_same_array,
     "同一の配列は交換できません"),
MSG (Earray_rank_mismatch,
     "配列のランクが異なります"),
MSG (Eno_rank_is_specified,
     "配列のランクが指定されていません"),
MSG (Eno_initializer_for_array,
     "配列の初期化オブジェクトがありません"),
MSG (Earray_initializer_count_mismatch,
     "配列の初期化オブジェクトの個数が異なっています"),
MSG (Ecannot_coerce_to_character,
     "文字への変換はサポートされていません"),
MSG (Einvalid_slot,
     "不正なスロットです"),
MSG (Estructure_includes_recursively,
     "構造体が再帰的にincludeされています"),
MSG (Ewrong_slot_description,
     "不正なスロット記述子です"),
MSG (Eis_typed_structure,
     "型付きの構造体です"),
MSG (Eend_of_file,
     "EOFに達しました"),
MSG (Eunknown_folder_name,
     "未定義のフォルダ名です"),
MSG (Eunknown_STRRET_type,
     "未定義のSTRRETタイプです"),
MSG (Ecomma_atsign_is_not_in_backquote,
     "‘,@’がバッククオート構文以外に現れました"),
MSG (Ecomma_dot_is_not_in_backquote,
     "‘,.’がバッククオート構文以外に現れました"),
MSG (Ecomma_is_not_in_backquote,
     "‘,’がバッククオート構文以外に現れました"),
MSG (Eunknown_c_type,
     "未定義のC型指定子です"),
MSG (Eunknown_calling_convention,
     "未定義の呼び出し規約です"),
MSG (Einvalid_c_argument_type,
     "引数の型が不正です"),
MSG (Einvalid_c_vaarg_type,
     "不正な可変長引数です"),
MSG (Ecannot_call_vaarg_function_by_stdcall,
     "stdcall呼び出し規約の場合、可変長引数は利用できません"),
MSG (Edll_not_initialized,
     "DLL関数は初期化されていません"),
MSG (Ewrong_function_bar_char,
     "指定された文字はファンクションバーに割り当てられません"),
MSG (Ebad_function_bar_label_number,
     "不正なファンクションバーのラベル数です"),
MSG (Einvalid_encoding_option,
     "不正な‘:encoding’オプションです"),
MSG (Einvalid_charset,
     "不正な文字セットです"),
MSG (Edde_undefined_return_type,
     "未定義のdde-request型です"),
MSG (EPDERR_INITFAILURE,
     "プリンタの初期化に失敗しました"),
MSG (EPDERR_LOADDRVFAILURE,
     "プリンタのデバイスドライバをロードできません"),
MSG (EPDERR_NODEFAULTPRN,
     "通常使うプリンタが設定されていません"),
MSG (EPDERR_NODEVICES,
     "プリンタドライバが見つかりません"),
MSG (EPDERR_PRINTERNOTFOUND,
     "プリンタが正しくインストールされていません"),
MSG (Esuffix_too_long,
     "拡張子が長すぎます"),
MSG (Mclumsy_backup_filename,
     "不細工なバックアップファイル名になってしまいました"),
MSG (Einvalid_share_option,
     "不正な‘:share’オプションです"),
MSG (Eprefix_too_long,
     "プリフィックスが長すぎます"),
MSG (ARC_ERROR_NOT_SUPPORT,
     "アーカイバ DLL でサポートされていません"),
MSG (Ecannot_convert_to_variant,
     "VARIANTに変換できません"),
MSG (Einvalid_idispatch,
     "不正なoledataです"),
MSG (Ecannot_convert_from_variant,
     "未サポートのVARIANTタイプです"),
MSG (Ereadtable_value_is_not_readtable,
     "*readtable*の値がリードテーブルではありません"),
MSG (Emacro_char_out_of_range,
     "範囲外のマクロ文字です"),
MSG (Edispmacro_sub_char_out_of_range,
     "範囲外のディスパッチングマクロ副文字です"),
MSG (Eis_not_a_dispmacro_char,
     "ディスパッチングマクロ文字ではありません"),
MSG (Enumeric_dispmacro_sub_char,
     "ディスパッチングマクロ副文字が数値です"),
MSG (Eis_not_a_macro_char,
     "マクロ文字ではありません"),
MSG (Eis_not_a_dispmacro_sub_char,
     "ディスパッチングマクロ副文字ではありません"),
MSG (Einvalid_readtable_case,
     "不正なreadtable-caseです"),
MSG (Eis_special_form,
     "特殊形式です"),
MSG (Einvalid_window_configuration,
     "不正なwindow-configurationです"),
MSG (Einvalid_doc_file,
     "DOCファイルが壊れています"),
MSG (Ecomplex_regexp,
     "もちっとシンプルな正規表現にしてください"),
MSG (Etarget_xyzzy_is_busy,
     "なんか忙しいみたいなんで、また後にしましょう"),
MSG (Euncompress_not_supported,
     "解凍はサポートしていません"),
MSG (Eunknown_charset,
     "不明な文字セットです"),
MSG (Eunsupported_charset,
     "未サポートの文字セットです"),
MSG (Eunsupported_codepage,
     "未サポートのコードページです"),
MSG (Eunknown_char_encoding,
     "不明なエンコードです"),
MSG (Enot_a_shortcut,
     "ショートカットではありません"),
MSG (Etimezone_is_integral_multiple_of_1_3600,
     "タイムゾーンは1/3600の整数倍です"),
MSG (Eremove_not_supported,
     "削除はサポートしていません"),
MSG (Eremove_error,
     "削除中にエラーが発生しました"),
MSG (Ecannot_open_bmp_file,
     "ファイルがオープンできません"),
MSG (Ebad_bmp_format,
     "認識できないビットマップファイルです"),
MSG (Eunsupported_bmp_format,
     "未サポートのビットマップファイル形式です"),
MSG (Ecannot_create_bitmap,
     "ビットマップが作成できません"),
MSG (ECannot_create_toolbar,
     "ツールバーが作成できません"),
MSG (Etoo_many_tool_items,
     "ツールボタンが多すぎます"),
MSG (Eno_tool_items,
     "ツールボタンが指定されていません"),
MSG (Etoolbar_exist,
     "ツールバーはすでに存在します"),
MSG (Eundefined_toolbar,
     "未定義のツールバーです"),
MSG (Enot_a_tab_bar,
     "タブバーではありません"),
MSG (Emultiple_position_specified,
     "タブの位置指定が不正です"),
MSG (Eno_event_sink,
     "EventSinkが定義されていません"),
MSG (Etab_not_found,
     "指定されたタブが見つかりません"),
MSG (Erename_failed,
     "すまんす。\n\n%s\nを\n%s\nにリネームできません。自力で何とかしてください。"),
MSG (ESHFileOperation_not_supported,
     "SHFileOperationはサポートされていません"),
MSG (Edelete_failed,
     "削除できません"),
MSG (Enot_in_gzip_format,
     "gzipフォーマットではありません"),
MSG (Egzip_data_error,
     "gzip data error"),
MSG (Eregexp_too_long,
     "正規表現が長すぎます"),
MSG (Ehtml_help_does_not_supported,
     "HtmlHelpはサポートされていません"),
MSG (Ehtml_help_error,
     "HtmlHelp"),
MSG (Einvalid_ienum_variant,
     "不正なoledataです"),
MSG (Ecreate_ienum_failed,
     "IEnumインターフェイスの取得に失敗しました"),
MSG (Einvalid_named_args_list,
     "不正な名前付き引数です"),
MSG (Eget_named_args_info_failed,
     "名前付き引数の情報取得に失敗しました。"),
MSG (Eunknown_verify_mode,
     "未定義の検証モードです"),
MSG (Eget_remote_cert_context_failed,
     "サーバ証明書の取得に失敗しました。"),
MSG (Eget_certificate_chain_failed,
     "証明書チェーンの取得に失敗しました。"),
MSG (Everify_certificate_chain_failed,
     "証明書チェーンの検証に失敗しました。"),
MSG (Einvalid_file_operation,
     "不正なファイル操作です"),
