#define N2S(x)			N2S_(x)
#define N2S_(x)			#x
#define XYZZY_VERSION		PROGRAM_MAJOR_VERSION,PROGRAM_MINOR_VERSION,PROGRAM_MAJOR_REVISION,PROGRAM_MINOR_REVISION
#define XYZZY_VERSION_STR	N2S(PROGRAM_MAJOR_VERSION) ", " N2S(PROGRAM_MINOR_VERSION) ", " N2S(PROGRAM_MAJOR_REVISION) ", " N2S(PROGRAM_MINOR_REVISION)

VS_VERSION_INFO VERSIONINFO
  FILEVERSION XYZZY_VERSION
  PRODUCTVERSION XYZZY_VERSION
  FILEFLAGSMASK 0x3fL
#ifdef DEBUG
  FILEFLAGS 0x1L
#else
  FILEFLAGS 0x0L
#endif
  FILEOS 0x40004L
  FILETYPE 0x1L
  FILESUBTYPE 0x0L
BEGIN
  BLOCK "StringFileInfo"
  BEGIN
    BLOCK "041104b0"
    BEGIN
      VALUE "CompanyName", " \0"
      VALUE "FileDescription", PROGRAM_NAME "\0"
      VALUE "FileVersion", XYZZY_VERSION_STR "\0"
      VALUE "InternalName", PROGRAM_NAME "\0"
      VALUE "LegalCopyright", PROGRAM_COPYRIGHT "\0"
      VALUE "OriginalFilename", PROGRAM_NAME ".exe\0"
      VALUE "ProductName", PROGRAM_NAME "\0"
      VALUE "ProductVersion", XYZZY_VERSION_STR "\0"
    END
  END
  BLOCK "VarFileInfo"
  BEGIN
    VALUE "Translation", 0x411, 1200
  END
END
